[tool.poetry]
name = "crimeradar-api"
version = "1.0.0"
description = ""


[tool.isort]
profile = "black"
src_paths = ["app"]

[tool.black]
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
line_length = 119
